[[Epsteinlib]]
arch = "aarch64"
git-tree-sha1 = "1a96612b95fb907434acf89769a94e7c21a34f1e"
os = "macos"

    [[Epsteinlib.download]]
    sha256 = "db8905e9087f86387f31b75c4b341ecece0bbe5140b98467591b59b9a16763d6"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.1+0/Epsteinlib.v0.5.1.aarch64-apple-darwin.tar.gz"
[[Epsteinlib]]
arch = "aarch64"
git-tree-sha1 = "69a547c89f237ce9bfb990eb30cef963af7f5748"
libc = "glibc"
os = "linux"

    [[Epsteinlib.download]]
    sha256 = "c2b1800499e979cdb11df17bbd8e27c984ab0ae2b6c9783782deb919692c2ab0"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.1+0/Epsteinlib.v0.5.1.aarch64-linux-gnu.tar.gz"
[[Epsteinlib]]
arch = "aarch64"
git-tree-sha1 = "47ba4f037cfea9911f1a0be95ee83d3c0fc51ca2"
libc = "musl"
os = "linux"

    [[Epsteinlib.download]]
    sha256 = "5c7301d6db29dea85a7a3a32f7baee610fe4c53a05f3945a1eb07608a805fce6"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.1+0/Epsteinlib.v0.5.1.aarch64-linux-musl.tar.gz"
[[Epsteinlib]]
arch = "aarch64"
git-tree-sha1 = "4bac0ba36a26363ee664e8e63ae40984c140d2c4"
os = "freebsd"

    [[Epsteinlib.download]]
    sha256 = "d29163a5eb6c6aa5679d0348a1ea69f1e2629be2bb0ecb674d1e1453b95ae70a"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.1+0/Epsteinlib.v0.5.1.aarch64-unknown-freebsd.tar.gz"
[[Epsteinlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1cf31691c3baa494458a138c541194ba6454abcb"
libc = "glibc"
os = "linux"

    [[Epsteinlib.download]]
    sha256 = "b7c420aac9a67eff6f3db925134bae6f725e3673dba805778720602279d3d474"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.1+0/Epsteinlib.v0.5.1.armv6l-linux-gnueabihf.tar.gz"
[[Epsteinlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "63e9e5202f5b137fb31ef248a0ed6b58f00e4da2"
libc = "musl"
os = "linux"

    [[Epsteinlib.download]]
    sha256 = "2d25f15272132f39d52027aa98a5757bc0f2137c695e28fe3886a2db8e965dcf"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.1+0/Epsteinlib.v0.5.1.armv6l-linux-musleabihf.tar.gz"
[[Epsteinlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "40cb12ba24d4611de13eafc6b8a03e54eaf065d0"
libc = "glibc"
os = "linux"

    [[Epsteinlib.download]]
    sha256 = "74161d40740104f5e6f92819e900563a63cb33c245ec350bb9514cf783f44477"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.1+0/Epsteinlib.v0.5.1.armv7l-linux-gnueabihf.tar.gz"
[[Epsteinlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ca387c10539662bc5f5285e354a8d7a83824c941"
libc = "musl"
os = "linux"

    [[Epsteinlib.download]]
    sha256 = "aa36037796f1e6d87cd6a96ac8b1257eb1f7c3107ae72c96fb2c00af50cc3a99"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.1+0/Epsteinlib.v0.5.1.armv7l-linux-musleabihf.tar.gz"
[[Epsteinlib]]
arch = "i686"
git-tree-sha1 = "a1196795da46dedc68d619e1fcb795b9259671fa"
libc = "glibc"
os = "linux"

    [[Epsteinlib.download]]
    sha256 = "f0e3fa7beb0e1339accaea67f024abc0506111018ed7ea16c382d4290eebb701"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.1+0/Epsteinlib.v0.5.1.i686-linux-gnu.tar.gz"
[[Epsteinlib]]
arch = "i686"
git-tree-sha1 = "9ba46a7d52c630ed99871b4fabfc9922a21bdb60"
libc = "musl"
os = "linux"

    [[Epsteinlib.download]]
    sha256 = "fc18c1735ae3adec8aa5654a48ff76e6ce9f753cc9a4514acd37cdce9afc2b80"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.1+0/Epsteinlib.v0.5.1.i686-linux-musl.tar.gz"
[[Epsteinlib]]
arch = "i686"
git-tree-sha1 = "6930d70107802f788889da061fd2fdb8a7a12e13"
os = "windows"

    [[Epsteinlib.download]]
    sha256 = "cb9137dbcc9673187167815e80d342289d8314135564bed5429a670961a1bb05"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.1+0/Epsteinlib.v0.5.1.i686-w64-mingw32.tar.gz"
[[Epsteinlib]]
arch = "powerpc64le"
git-tree-sha1 = "5b39111bd8ba57a398f9f09cf7c57112af37e357"
libc = "glibc"
os = "linux"

    [[Epsteinlib.download]]
    sha256 = "ddc0741e7ad03b5b21569f762e8c147ff771ea31c2dc060c91f09413cbdac531"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.1+0/Epsteinlib.v0.5.1.powerpc64le-linux-gnu.tar.gz"
[[Epsteinlib]]
arch = "riscv64"
git-tree-sha1 = "657d0ed3c7f6de4ce87b6329b002ed5cfde90693"
libc = "glibc"
os = "linux"

    [[Epsteinlib.download]]
    sha256 = "055634ffc0d98c6a022d97fcc37151f77326565cf160a9ab727317f0b7906a38"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.1+0/Epsteinlib.v0.5.1.riscv64-linux-gnu.tar.gz"
[[Epsteinlib]]
arch = "x86_64"
git-tree-sha1 = "2670673584fe574e6d7a160f5b1e920b985a9fd0"
os = "macos"

    [[Epsteinlib.download]]
    sha256 = "8fbc230c550e8eb6b363cd5f8e3e50fe57392d0605f70a519a8259ed077ae85d"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.1+0/Epsteinlib.v0.5.1.x86_64-apple-darwin.tar.gz"
[[Epsteinlib]]
arch = "x86_64"
git-tree-sha1 = "6de9d19a5c4f34039343aa8219de218e1b3624f9"
libc = "glibc"
os = "linux"

    [[Epsteinlib.download]]
    sha256 = "9413a220339ab065f4300d9488184c7ea25507bc47ca653161d9caf479f475c2"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.1+0/Epsteinlib.v0.5.1.x86_64-linux-gnu.tar.gz"
[[Epsteinlib]]
arch = "x86_64"
git-tree-sha1 = "13050800b8e1328eac8c2aa0e08318e4d5f0d86c"
libc = "musl"
os = "linux"

    [[Epsteinlib.download]]
    sha256 = "692b8fcd693abd92ee7dc706c2bfa88cf9231352e1ef1b99858f294756ff4fb6"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.1+0/Epsteinlib.v0.5.1.x86_64-linux-musl.tar.gz"
[[Epsteinlib]]
arch = "x86_64"
git-tree-sha1 = "d4a648247fc7228c90477e9b39e470b686e147b6"
os = "freebsd"

    [[Epsteinlib.download]]
    sha256 = "4d085a116f11e2d49dbad32869d153354e5ce9d663e9eea237e54c4b84cccaca"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.1+0/Epsteinlib.v0.5.1.x86_64-unknown-freebsd.tar.gz"
[[Epsteinlib]]
arch = "x86_64"
git-tree-sha1 = "bddb371b8fbb0192faa57feac133baf671d2eb2b"
os = "windows"

    [[Epsteinlib.download]]
    sha256 = "6e9c0a0190ed8c3e37d3d546d0e94531f19aae62b11f48826020c6d584f6cfc1"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.1+0/Epsteinlib.v0.5.1.x86_64-w64-mingw32.tar.gz"
