[[Epsteinlib]]
arch = "aarch64"
git-tree-sha1 = "025aaa4e7859de71e4a49e98be7a0aa18efb9309"
os = "macos"

    [[Epsteinlib.download]]
    sha256 = "a78444c438eac4b17b79a8b54e5c31f7657b8900878d8cf4bb3e224e28f6f9dc"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.0+0/Epsteinlib.v0.5.0.aarch64-apple-darwin.tar.gz"
[[Epsteinlib]]
arch = "aarch64"
git-tree-sha1 = "1f7c84277e7c91b7cac76fd5fbb785af36938491"
libc = "glibc"
os = "linux"

    [[Epsteinlib.download]]
    sha256 = "7ac9dd0063ff145eb972951860a7cdf7314bcc00f0d25cda0edd34c86191c455"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.0+0/Epsteinlib.v0.5.0.aarch64-linux-gnu.tar.gz"
[[Epsteinlib]]
arch = "aarch64"
git-tree-sha1 = "0d17d39e06a44d8b6d18d0ce1c4662ddb6bffdd4"
libc = "musl"
os = "linux"

    [[Epsteinlib.download]]
    sha256 = "9eae9273a746a7c3e9db0068138724e5e8376d006c501299014bb7b76a14fe74"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.0+0/Epsteinlib.v0.5.0.aarch64-linux-musl.tar.gz"
[[Epsteinlib]]
arch = "aarch64"
git-tree-sha1 = "547fd85908972e3abae555bb3a1e292fd2785b55"
os = "freebsd"

    [[Epsteinlib.download]]
    sha256 = "88cadd4637e78c6981b761b63ce89e6ff3968f5eb4b59a2920fbdb328fa2a8df"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.0+0/Epsteinlib.v0.5.0.aarch64-unknown-freebsd.tar.gz"
[[Epsteinlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a2b74158c19e16956fa312f0dc4a5403160e5321"
libc = "glibc"
os = "linux"

    [[Epsteinlib.download]]
    sha256 = "51788787fe5c616b3911885a8a5d51f0193b10e9506db285fd51546e36d7eb83"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.0+0/Epsteinlib.v0.5.0.armv6l-linux-gnueabihf.tar.gz"
[[Epsteinlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "24d4ef9b2cfc53ba565bd1175cf010893e8aebba"
libc = "musl"
os = "linux"

    [[Epsteinlib.download]]
    sha256 = "dc90eaa571deaaeaac13043d1885a4ec449497f8462e3ae0372678ed4b223488"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.0+0/Epsteinlib.v0.5.0.armv6l-linux-musleabihf.tar.gz"
[[Epsteinlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d1115e497347e569a0768b0d06a8978adeecf97a"
libc = "glibc"
os = "linux"

    [[Epsteinlib.download]]
    sha256 = "91ead917dc87342fe7e75a6176f84e188fef3d2bc0d6592a3483d1d617a546d0"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.0+0/Epsteinlib.v0.5.0.armv7l-linux-gnueabihf.tar.gz"
[[Epsteinlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "47de5aec6c008a4e5ff6cb964ffa82098c90727e"
libc = "musl"
os = "linux"

    [[Epsteinlib.download]]
    sha256 = "c46cc3811fd8b5f80c68a5cc8076564b309a4ad1b9ec95ddf105fa230da857a1"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.0+0/Epsteinlib.v0.5.0.armv7l-linux-musleabihf.tar.gz"
[[Epsteinlib]]
arch = "i686"
git-tree-sha1 = "5baf7a0f73c636c5ff3f720ba3af4cedd6b10c9b"
libc = "glibc"
os = "linux"

    [[Epsteinlib.download]]
    sha256 = "3e692f7b8fd7db64b07eb862d0d78e5fa40433a697cd42a9b9ad3b0a3fd6c507"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.0+0/Epsteinlib.v0.5.0.i686-linux-gnu.tar.gz"
[[Epsteinlib]]
arch = "i686"
git-tree-sha1 = "fb723821ed9e121a09faa953de758cf4aabba195"
libc = "musl"
os = "linux"

    [[Epsteinlib.download]]
    sha256 = "c9c1ff2e872f8bd22c1bd534dd8eee05d4aae8ffd67853b1a8dc05331227b3c8"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.0+0/Epsteinlib.v0.5.0.i686-linux-musl.tar.gz"
[[Epsteinlib]]
arch = "i686"
git-tree-sha1 = "0b75a718f8d3532b53e25339f238c5c262c68b3e"
os = "windows"

    [[Epsteinlib.download]]
    sha256 = "9b3840baca36966d50291de30f2f7520379b37c6b3df04712204ac093f00cfc0"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.0+0/Epsteinlib.v0.5.0.i686-w64-mingw32.tar.gz"
[[Epsteinlib]]
arch = "powerpc64le"
git-tree-sha1 = "2530ff9737d53689e7ee441d3d57e6b0241ce309"
libc = "glibc"
os = "linux"

    [[Epsteinlib.download]]
    sha256 = "1f8f9f68597cbdb99850f1f3b447c704e14debd6eb83ad9e203c2e8ea8736d9a"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.0+0/Epsteinlib.v0.5.0.powerpc64le-linux-gnu.tar.gz"
[[Epsteinlib]]
arch = "riscv64"
git-tree-sha1 = "8cb93f85854fac4f2c2fdd9262f470df95ddd799"
libc = "glibc"
os = "linux"

    [[Epsteinlib.download]]
    sha256 = "1c3753ea236981cda533879800f399323d02f698abe79cafa027a52dfa39c3bc"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.0+0/Epsteinlib.v0.5.0.riscv64-linux-gnu.tar.gz"
[[Epsteinlib]]
arch = "x86_64"
git-tree-sha1 = "c0775774596f35997fa088b52dd43c82d5cc8ab1"
os = "macos"

    [[Epsteinlib.download]]
    sha256 = "cb45dcc452c22b9caa4b2d489c64af61e0b1d975f1baf1317fdf4e2c34396811"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.0+0/Epsteinlib.v0.5.0.x86_64-apple-darwin.tar.gz"
[[Epsteinlib]]
arch = "x86_64"
git-tree-sha1 = "3700870a31e9e03d05cb57f044abfe80e149f789"
libc = "glibc"
os = "linux"

    [[Epsteinlib.download]]
    sha256 = "d4b4c49266aabec489a540e2beab4a5226ada0a8b7d406d59faa302300218091"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.0+0/Epsteinlib.v0.5.0.x86_64-linux-gnu.tar.gz"
[[Epsteinlib]]
arch = "x86_64"
git-tree-sha1 = "d14837ac2f812798301e4c25ec38ccac5c0acf94"
libc = "musl"
os = "linux"

    [[Epsteinlib.download]]
    sha256 = "2315ed3ed8b241a27e63c8539f233f520b182966ac64979b0947bb9e80c31dc4"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.0+0/Epsteinlib.v0.5.0.x86_64-linux-musl.tar.gz"
[[Epsteinlib]]
arch = "x86_64"
git-tree-sha1 = "6b4deb94acf04726a4e1935ec0161882418f162e"
os = "freebsd"

    [[Epsteinlib.download]]
    sha256 = "6c7373938728af0a72c5123b23736328929bee554fd32fc9f1cf1f8f1afa96a8"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.0+0/Epsteinlib.v0.5.0.x86_64-unknown-freebsd.tar.gz"
[[Epsteinlib]]
arch = "x86_64"
git-tree-sha1 = "13e5978b910839839f9a2f7d25759ae1da259d89"
os = "windows"

    [[Epsteinlib.download]]
    sha256 = "e7f7233e0847aaf5815983186f0874591d636a72768c15428978243f4ea52663"
    url = "https://github.com/JuliaBinaryWrappers/Epsteinlib_jll.jl/releases/download/Epsteinlib-v0.5.0+0/Epsteinlib.v0.5.0.x86_64-w64-mingw32.tar.gz"
