# Autogenerated wrapper script for Epsteinlib_jll for armv7l-linux-gnueabihf
export epsteinlib_c_lattice_sum, libepstein

JLLWrappers.@generate_wrapper_header("Epsteinlib")
JLLWrappers.@declare_library_product(libepstein, "libepstein.so")
JLLWrappers.@declare_executable_product(epsteinlib_c_lattice_sum)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libepstein,
        "lib/libepstein.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        epsteinlib_c_lattice_sum,
        "bin/epsteinlib_c-lattice_sum",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
