# Autogenerated wrapper script for Epsteinlib_jll for x86_64-w64-mingw32
export epsteinlib_c_lattice_sum, libepstein

JLLWrappers.@generate_wrapper_header("Epsteinlib")
JLLWrappers.@declare_library_product(libepstein, "libepstein.dll")
JLLWrappers.@declare_executable_product(epsteinlib_c_lattice_sum)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libepstein,
        "bin\\libepstein.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        epsteinlib_c_lattice_sum,
        "bin\\epsteinlib_c-lattice_sum.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
